import type {
  ExchangeRateSnapshot,
  PricingCatalog,
  PricingRule,
} from "./pricingTypes.ts";
import { getSerializableQuestionnaireContract } from "./serviceQuestionnaires.ts";

const contextRules = (servicePrefix: string): PricingRule[] => [
  {
    id: `${servicePrefix}-established-governance`,
    input: { scope: "shared-profile", key: "organizationScale" },
    dimension: "validation",
    label: { fr: "Gouvernance d’une entreprise établie", en: "Established-company governance" },
    when: { operator: "equals", value: "established" },
    operation: "multiply-bps",
    lowerBasisPoints: 10_500,
    upperBasisPoints: 11_000,
  },
  {
    id: `${servicePrefix}-large-organization-governance`,
    input: { scope: "shared-profile", key: "organizationScale" },
    dimension: "validation",
    label: { fr: "Gouvernance d’une grande organisation", en: "Large-organisation governance" },
    when: { operator: "equals", value: "large-institution" },
    operation: "multiply-bps",
    lowerBasisPoints: 11_250,
    upperBasisPoints: 12_500,
  },
  {
    id: `${servicePrefix}-uemoa-coordination`,
    input: { scope: "shared-profile", key: "clientLocation" },
    dimension: "complexity",
    label: { fr: "Coordination UEMOA hors Bénin", en: "WAEMU coordination outside Benin" },
    when: { operator: "equals", value: "uemoa" },
    operation: "multiply-bps",
    lowerBasisPoints: 10_500,
    upperBasisPoints: 11_250,
  },
  {
    id: `${servicePrefix}-africa-coordination`,
    input: { scope: "shared-profile", key: "clientLocation" },
    dimension: "complexity",
    label: { fr: "Coordination africaine hors UEMOA", en: "African coordination outside WAEMU" },
    when: { operator: "equals", value: "africa" },
    operation: "multiply-bps",
    lowerBasisPoints: 11_250,
    upperBasisPoints: 12_500,
  },
  {
    id: `${servicePrefix}-international-coordination`,
    input: { scope: "shared-profile", key: "clientLocation" },
    dimension: "complexity",
    label: { fr: "Coordination internationale", en: "International coordination" },
    when: { operator: "equals", value: "international" },
    operation: "multiply-bps",
    lowerBasisPoints: 12_500,
    upperBasisPoints: 14_500,
  },
  {
    id: `${servicePrefix}-idea-framing`,
    input: { scope: "shared-profile", key: "projectStage" },
    dimension: "complexity",
    label: { fr: "Cadrage d’un projet émergent", en: "Early-stage project framing" },
    when: { operator: "equals", value: "idea" },
    operation: "multiply-bps",
    lowerBasisPoints: 11_000,
    upperBasisPoints: 12_000,
  },
  {
    id: `${servicePrefix}-repositioning-complexity`,
    input: { scope: "shared-profile", key: "projectStage" },
    dimension: "complexity",
    label: { fr: "Complexité de repositionnement", en: "Repositioning complexity" },
    when: { operator: "equals", value: "repositioning" },
    operation: "multiply-bps",
    lowerBasisPoints: 11_000,
    upperBasisPoints: 12_500,
  },
  {
    id: `${servicePrefix}-national-market`,
    input: { scope: "shared-profile", key: "marketScope" },
    dimension: "volume",
    label: { fr: "Périmètre national", en: "National market scope" },
    when: { operator: "equals", value: "national" },
    operation: "multiply-bps",
    lowerBasisPoints: 10_500,
    upperBasisPoints: 11_000,
  },
  {
    id: `${servicePrefix}-regional-market`,
    input: { scope: "shared-profile", key: "marketScope" },
    dimension: "volume",
    label: { fr: "Périmètre régional", en: "Regional market scope" },
    when: { operator: "equals", value: "regional" },
    operation: "multiply-bps",
    lowerBasisPoints: 11_250,
    upperBasisPoints: 12_500,
  },
  {
    id: `${servicePrefix}-international-market`,
    input: { scope: "shared-profile", key: "marketScope" },
    dimension: "volume",
    label: { fr: "Périmètre international", en: "International market scope" },
    when: { operator: "equals", value: "international" },
    operation: "multiply-bps",
    lowerBasisPoints: 12_500,
    upperBasisPoints: 14_500,
  },
  {
    id: `${servicePrefix}-two-languages`,
    input: { scope: "shared-profile", key: "languageScope" },
    dimension: "volume",
    label: { fr: "Production bilingue", en: "Bilingual delivery" },
    when: { operator: "equals", value: "two" },
    operation: "multiply-bps",
    lowerBasisPoints: 11_250,
    upperBasisPoints: 12_000,
  },
  {
    id: `${servicePrefix}-three-languages`,
    input: { scope: "shared-profile", key: "languageScope" },
    dimension: "volume",
    label: { fr: "Production en trois langues ou plus", en: "Delivery in three or more languages" },
    when: { operator: "equals", value: "three-plus" },
    operation: "multiply-bps",
    lowerBasisPoints: 12_500,
    upperBasisPoints: 14_000,
  },
  {
    id: `${servicePrefix}-unknown-language-scope`,
    input: { scope: "shared-profile", key: "languageScope" },
    dimension: "complexity",
    label: { fr: "Langues à cadrer", en: "Languages need scoping" },
    when: { operator: "equals", value: "unknown" },
    operation: "manual-review",
    reasonCode: "language-scope-to-confirm",
  },
  {
    id: `${servicePrefix}-urgent-start`,
    input: { scope: "shared-profile", key: "timeline" },
    dimension: "urgency",
    label: { fr: "Démarrage sous deux semaines", en: "Start within two weeks" },
    when: { operator: "equals", value: "urgent" },
    operation: "multiply-bps",
    lowerBasisPoints: 12_000,
    upperBasisPoints: 13_500,
  },
  {
    id: `${servicePrefix}-two-three-approvers`,
    input: { scope: "shared-profile", key: "validationProcess" },
    dimension: "validation",
    label: { fr: "Validation par deux à trois personnes", en: "Two to three approvers" },
    when: { operator: "equals", value: "two-three" },
    operation: "multiply-bps",
    lowerBasisPoints: 10_500,
    upperBasisPoints: 11_000,
  },
  {
    id: `${servicePrefix}-four-plus-approvers`,
    input: { scope: "shared-profile", key: "validationProcess" },
    dimension: "validation",
    label: { fr: "Circuit de validation étendu", en: "Extended approval workflow" },
    when: { operator: "equals", value: "four-plus" },
    operation: "multiply-bps",
    lowerBasisPoints: 11_500,
    upperBasisPoints: 12_500,
  },
  {
    id: `${servicePrefix}-unknown-validation-process`,
    input: { scope: "shared-profile", key: "validationProcess" },
    dimension: "complexity",
    label: { fr: "Circuit de validation à cadrer", en: "Approval workflow needs scoping" },
    when: { operator: "equals", value: "unknown" },
    operation: "manual-review",
    reasonCode: "validation-process-to-confirm",
  },
];

const editorialRules: PricingRule[] = [
  { id: "editorial-revision", input: { scope: "service-question", key: "editorial.currentState" }, dimension: "complexity", label: { fr: "Révision d’une stratégie existante", en: "Existing-strategy revision" }, when: { operator: "equals", value: "revision" }, operation: "add-range", rangeXof: { lower: 30_000, upper: 60_000 } },
  { id: "editorial-brands-two-three", input: { scope: "service-question", key: "editorial.brandCount" }, dimension: "volume", label: { fr: "Deux à trois marques ou offres", en: "Two to three brands or offers" }, when: { operator: "equals", value: "two-three" }, operation: "add-range", rangeXof: { lower: 100_000, upper: 180_000 } },
  { id: "editorial-brands-four-plus", input: { scope: "service-question", key: "editorial.brandCount" }, dimension: "volume", label: { fr: "Quatre marques ou offres ou plus", en: "Four or more brands or offers" }, when: { operator: "equals", value: "four-plus" }, operation: "add-range", rangeXof: { lower: 150_000, upper: 270_000 } },
  { id: "editorial-brands-unknown", input: { scope: "service-question", key: "editorial.brandCount" }, dimension: "complexity", label: { fr: "Périmètre de marques à préciser", en: "Brand scope to be clarified" }, when: { operator: "equals", value: "unknown" }, operation: "add-range", rangeXof: { lower: 50_000, upper: 90_000 } },
  { id: "editorial-audiences-four-plus", input: { scope: "service-question", key: "editorial.audienceCount" }, dimension: "volume", label: { fr: "Plusieurs groupes de publics à distinguer", en: "Several audience groups to distinguish" }, when: { operator: "equals", value: "four-plus" }, operation: "add-range", rangeXof: { lower: 50_000, upper: 90_000 } },
  { id: "editorial-corpus-medium", input: { scope: "service-question", key: "editorial.existingCorpusSize" }, dimension: "volume", label: { fr: "Analyse d’un ensemble moyen de contenus", en: "Review of a medium content set" }, when: { operator: "equals", value: "eleven-thirty" }, operation: "add-range", rangeXof: { lower: 30_000, upper: 60_000 } },
  { id: "editorial-corpus-large", input: { scope: "service-question", key: "editorial.existingCorpusSize" }, dimension: "volume", label: { fr: "Analyse d’un ensemble important de contenus", en: "Review of a large content set" }, when: { operator: "equals", value: "thirty-plus" }, operation: "add-range", rangeXof: { lower: 60_000, upper: 120_000 } },
  { id: "editorial-focused-benchmark", input: { scope: "service-question", key: "editorial.benchmarkScope" }, dimension: "options", label: { fr: "Benchmark ciblé", en: "Focused benchmark" }, when: { operator: "equals", value: "focused" }, operation: "add-range", rangeXof: { lower: 30_000, upper: 50_000 } },
  { id: "editorial-extended-benchmark", input: { scope: "service-question", key: "editorial.benchmarkScope" }, dimension: "options", label: { fr: "Benchmark étendu", en: "Extended benchmark" }, when: { operator: "equals", value: "extended" }, operation: "add-range", rangeXof: { lower: 70_000, upper: 120_000 } },
  { id: "editorial-charter", input: { scope: "service-question", key: "editorial.deliverables" }, dimension: "options", label: { fr: "Charte éditoriale", en: "Editorial guidelines" }, when: { operator: "includes", value: "editorial-charter" }, operation: "add-range", rangeXof: { lower: 40_000, upper: 70_000 } },
  { id: "editorial-angle-bank", input: { scope: "service-question", key: "editorial.deliverables" }, dimension: "options", label: { fr: "Banque d’angles et de sujets", en: "Content angle and topic bank" }, when: { operator: "includes", value: "angle-bank" }, operation: "add-range", rangeXof: { lower: 30_000, upper: 60_000 } },
  { id: "editorial-channel-rules", input: { scope: "service-question", key: "editorial.deliverables" }, dimension: "options", label: { fr: "Règles par canal", en: "Channel-specific rules" }, when: { operator: "includes", value: "channel-rules" }, operation: "add-range", rangeXof: { lower: 30_000, upper: 60_000 } },
  { id: "editorial-workshop", input: { scope: "service-question", key: "editorial.discoveryMethod" }, dimension: "options", label: { fr: "Atelier collectif", en: "Group workshop" }, when: { operator: "includes", value: "workshop" }, operation: "add-range", rangeXof: { lower: 45_000, upper: 80_000 } },
  { id: "editorial-interviews", input: { scope: "service-question", key: "editorial.discoveryMethod" }, dimension: "volume", label: { fr: "Échanges avec les personnes concernées", en: "Conversations with relevant people" }, when: { operator: "includes", value: "interviews" }, operation: "add-range", rangeXof: { lower: 40_000, upper: 70_000 } },
  { id: "editorial-presentation", input: { scope: "service-question", key: "editorial.deliverables" }, dimension: "options", label: { fr: "Présentation de la stratégie", en: "Strategy presentation" }, when: { operator: "includes", value: "presentation" }, operation: "add-range", rangeXof: { lower: 25_000, upper: 45_000 } },
  { id: "editorial-training", input: { scope: "service-question", key: "editorial.deliverables" }, dimension: "options", label: { fr: "Formation de l’équipe", en: "Team training" }, when: { operator: "includes", value: "team-training" }, operation: "add-range", rangeXof: { lower: 70_000, upper: 120_000 } },
  { id: "editorial-follow-up", input: { scope: "service-question", key: "editorial.deliverables" }, dimension: "options", label: { fr: "Suivi après remise", en: "Post-delivery follow-up" }, when: { operator: "includes", value: "follow-up" }, operation: "add-range", rangeXof: { lower: 60_000, upper: 100_000 } },
  { id: "editorial-recommended-framework", input: { scope: "service-question", key: "editorial.deliverables" }, dimension: "options", label: { fr: "Cadre éditorial complet recommandé", en: "Recommended complete editorial framework" }, when: { operator: "includes", value: "recommended" }, operation: "add-range", rangeXof: { lower: 120_000, upper: 220_000 } },
  ...contextRules("editorial"),
];

const communicationRules: PricingRule[] = [
  { id: "communication-launch", input: { scope: "service-question", key: "communication.engagementType" }, dimension: "duration", label: { fr: "Dispositif de lancement", en: "Launch program" }, when: { operator: "equals", value: "launch" }, operation: "add-range", rangeXof: { lower: 50_000, upper: 90_000 } },
  { id: "communication-campaign", input: { scope: "service-question", key: "communication.engagementType" }, dimension: "duration", label: { fr: "Dispositif de campagne", en: "Campaign program" }, when: { operator: "equals", value: "campaign" }, operation: "add-range", rangeXof: { lower: 40_000, upper: 80_000 } },
  { id: "communication-event", input: { scope: "service-question", key: "communication.engagementType" }, dimension: "duration", label: { fr: "Dispositif événementiel", en: "Event program" }, when: { operator: "equals", value: "event" }, operation: "add-range", rangeXof: { lower: 70_000, upper: 130_000 } },
  { id: "communication-accounts-two-three", input: { scope: "service-question", key: "communication.accountCount" }, dimension: "volume", label: { fr: "Deux à trois comptes", en: "Two to three accounts" }, when: { operator: "equals", value: "two-three" }, operation: "add-range", rangeXof: { lower: 25_000, upper: 45_000 } },
  { id: "communication-accounts-four-six", input: { scope: "service-question", key: "communication.accountCount" }, dimension: "volume", label: { fr: "Quatre à six comptes", en: "Four to six accounts" }, when: { operator: "equals", value: "four-six" }, operation: "add-range", rangeXof: { lower: 75_000, upper: 135_000 } },
  { id: "communication-accounts-seven-plus", input: { scope: "service-question", key: "communication.accountCount" }, dimension: "volume", label: { fr: "Sept comptes ou plus", en: "Seven accounts or more" }, when: { operator: "equals", value: "seven-plus" }, operation: "add-range", rangeXof: { lower: 150_000, upper: 270_000 } },
  { id: "communication-duration-three", input: { scope: "service-question", key: "communication.durationMonths" }, dimension: "duration", label: { fr: "Accompagnement de trois mois", en: "Three-month engagement" }, when: { operator: "equals", value: "three" }, operation: "add-range", rangeXof: { lower: 180_000, upper: 320_000 } },
  { id: "communication-duration-six", input: { scope: "service-question", key: "communication.durationMonths" }, dimension: "duration", label: { fr: "Accompagnement de six mois", en: "Six-month engagement" }, when: { operator: "equals", value: "six" }, operation: "add-range", rangeXof: { lower: 450_000, upper: 800_000 } },
  { id: "communication-duration-twelve-plus", input: { scope: "service-question", key: "communication.durationMonths" }, dimension: "duration", label: { fr: "Accompagnement annuel", en: "Annual engagement" }, when: { operator: "equals", value: "twelve-plus" }, operation: "add-range", rangeXof: { lower: 990_000, upper: 1_760_000 } },
  { id: "communication-rhythm-regular", input: { scope: "service-question", key: "communication.postsPerMonth" }, dimension: "volume", label: { fr: "Rythme régulier de publication", en: "Regular publishing rhythm" }, when: { operator: "equals", value: "regular" }, operation: "add-range", rangeXof: { lower: 28_000, upper: 60_000 } },
  { id: "communication-rhythm-sustained", input: { scope: "service-question", key: "communication.postsPerMonth" }, dimension: "volume", label: { fr: "Rythme soutenu de publication", en: "Sustained publishing rhythm" }, when: { operator: "equals", value: "sustained" }, operation: "add-range", rangeXof: { lower: 56_000, upper: 120_000 } },
  { id: "communication-rhythm-intensive", input: { scope: "service-question", key: "communication.postsPerMonth" }, dimension: "volume", label: { fr: "Rythme intensif de publication", en: "Intensive publishing rhythm" }, when: { operator: "equals", value: "intensive" }, operation: "add-range", rangeXof: { lower: 112_000, upper: 240_000 } },
  { id: "communication-carole-content", input: { scope: "service-question", key: "communication.contentResponsibility" }, dimension: "complexity", label: { fr: "Production de contenu pilotée par Carole", en: "Content production led by Carole" }, when: { operator: "equals", value: "carole" }, operation: "add-range", rangeXof: { lower: 80_000, upper: 160_000 } },
  { id: "communication-mixed-content", input: { scope: "service-question", key: "communication.contentResponsibility" }, dimension: "complexity", label: { fr: "Production de contenu partagée", en: "Shared content production" }, when: { operator: "equals", value: "mixed" }, operation: "add-range", rangeXof: { lower: 40_000, upper: 90_000 } },
  { id: "communication-campaign-management", input: { scope: "service-question", key: "communication.tasks" }, dimension: "options", label: { fr: "Pilotage de campagne", en: "Campaign management" }, when: { operator: "includes", value: "campaign-management" }, operation: "add-range", rangeXof: { lower: 40_000, upper: 80_000 } },
  { id: "communication-vendor-management", input: { scope: "service-question", key: "communication.tasks" }, dimension: "options", label: { fr: "Coordination de prestataires", en: "Vendor coordination" }, when: { operator: "includes", value: "vendor-management" }, operation: "add-range", rangeXof: { lower: 30_000, upper: 60_000 } },
  { id: "communication-community-standard", input: { scope: "service-question", key: "communication.communityManagement" }, dimension: "options", label: { fr: "Animation communautaire standard", en: "Standard community management" }, when: { operator: "equals", value: "standard" }, operation: "add-range", rangeXof: { lower: 30_000, upper: 60_000 } },
  { id: "communication-community-extended", input: { scope: "service-question", key: "communication.communityManagement" }, dimension: "options", label: { fr: "Animation communautaire étendue", en: "Extended community management" }, when: { operator: "equals", value: "extended" }, operation: "add-range", rangeXof: { lower: 70_000, upper: 130_000 } },
  { id: "communication-paid-creative", input: { scope: "service-question", key: "communication.paidMedia" }, dimension: "options", label: { fr: "Coordination créative média payant", en: "Paid-media creative coordination" }, when: { operator: "equals", value: "creative-coordination" }, operation: "add-range", rangeXof: { lower: 40_000, upper: 80_000 } },
  { id: "communication-paid-strategy", input: { scope: "service-question", key: "communication.paidMedia" }, dimension: "options", label: { fr: "Stratégie média payant", en: "Paid-media strategy" }, when: { operator: "equals", value: "strategy" }, operation: "add-range", rangeXof: { lower: 80_000, upper: 150_000 } },
  { id: "communication-report-recommendations", input: { scope: "service-question", key: "communication.tasks" }, dimension: "options", label: { fr: "Suivi et recommandations", en: "Performance review and recommendations" }, when: { operator: "includes", value: "reporting-recommendations" }, operation: "add-range", rangeXof: { lower: 40_000, upper: 70_000 } },
  { id: "communication-report-meeting", input: { scope: "service-question", key: "communication.tasks" }, dimension: "options", label: { fr: "Réunion régulière de restitution", en: "Regular review meeting" }, when: { operator: "includes", value: "reporting-meeting" }, operation: "add-range", rangeXof: { lower: 30_000, upper: 60_000 } },
  { id: "communication-recommended-management", input: { scope: "service-question", key: "communication.tasks" }, dimension: "options", label: { fr: "Gestion complète recommandée", en: "Recommended full management" }, when: { operator: "includes", value: "recommended" }, operation: "add-range", rangeXof: { lower: 120_000, upper: 220_000 } },
  ...contextRules("communication"),
];

const contentRules: PricingRule[] = [
  { id: "content-volume-five-ten", input: { scope: "service-question", key: "content.totalVolume" }, dimension: "volume", label: { fr: "Lot de cinq à dix contenus", en: "Batch of five to ten content items" }, when: { operator: "equals", value: "five-ten" }, operation: "add-range", rangeXof: { lower: 48_000, upper: 120_000 } },
  { id: "content-volume-eleven-twenty", input: { scope: "service-question", key: "content.totalVolume" }, dimension: "volume", label: { fr: "Lot de onze à vingt contenus", en: "Batch of eleven to twenty content items" }, when: { operator: "equals", value: "eleven-twenty" }, operation: "add-range", rangeXof: { lower: 96_000, upper: 240_000 } },
  { id: "content-volume-twenty-plus", input: { scope: "service-question", key: "content.totalVolume" }, dimension: "volume", label: { fr: "Production de plus de vingt contenus", en: "Production of more than twenty content items" }, when: { operator: "equals", value: "twenty-plus" }, operation: "add-range", rangeXof: { lower: 240_000, upper: 600_000 } },
  { id: "content-article", input: { scope: "service-question", key: "content.formats" }, dimension: "complexity", label: { fr: "Article long", en: "Long-form article" }, when: { operator: "includes", value: "article" }, operation: "add-range", rangeXof: { lower: 20_000, upper: 40_000 } },
  { id: "content-carousel", input: { scope: "service-question", key: "content.formats" }, dimension: "complexity", label: { fr: "Carrousel", en: "Carousel" }, when: { operator: "includes", value: "carousel" }, operation: "add-range", rangeXof: { lower: 15_000, upper: 30_000 } },
  { id: "content-short-video-script", input: { scope: "service-question", key: "content.formats" }, dimension: "complexity", label: { fr: "Script vidéo courte", en: "Short-video script" }, when: { operator: "includes", value: "short-video-script" }, operation: "add-range", rangeXof: { lower: 15_000, upper: 30_000 } },
  { id: "content-static-visual", input: { scope: "service-question", key: "content.formats" }, dimension: "complexity", label: { fr: "Visuel statique", en: "Static visual" }, when: { operator: "includes", value: "static-visual" }, operation: "add-range", rangeXof: { lower: 15_000, upper: 30_000 } },
  { id: "content-short-video", input: { scope: "service-question", key: "content.formats" }, dimension: "complexity", label: { fr: "Vidéo courte", en: "Short-form video" }, when: { operator: "includes", value: "short-video" }, operation: "add-range", rangeXof: { lower: 50_000, upper: 120_000 } },
  { id: "content-partial-source", input: { scope: "service-question", key: "content.sourceMaterial" }, dimension: "complexity", label: { fr: "Création originale à partir d’une matière partielle", en: "Original creation from partial source material" }, when: { operator: "equals", value: "partial" }, operation: "add-range", rangeXof: { lower: 40_000, upper: 80_000 } },
  { id: "content-ideas-source", input: { scope: "service-question", key: "content.sourceMaterial" }, dimension: "complexity", label: { fr: "Développement à partir d’idées", en: "Development from initial ideas" }, when: { operator: "equals", value: "ideas-only" }, operation: "add-range", rangeXof: { lower: 30_000, upper: 60_000 } },
  { id: "content-interview-source", input: { scope: "service-question", key: "content.sourceMaterial" }, dimension: "options", label: { fr: "Collecte par entretiens", en: "Interview-led sourcing" }, when: { operator: "equals", value: "interviews" }, operation: "add-range", rangeXof: { lower: 40_000, upper: 80_000 } },
  { id: "content-research", input: { scope: "service-question", key: "content.sourceMaterial" }, dimension: "options", label: { fr: "Recherche documentaire", en: "Desk research" }, when: { operator: "equals", value: "research" }, operation: "add-range", rangeXof: { lower: 60_000, upper: 120_000 } },
  { id: "content-adapt-templates", input: { scope: "service-question", key: "content.visualTemplates" }, dimension: "options", label: { fr: "Adaptation des gabarits", en: "Template adaptation" }, when: { operator: "equals", value: "adapt" }, operation: "add-range", rangeXof: { lower: 15_000, upper: 30_000 } },
  { id: "content-create-templates", input: { scope: "service-question", key: "content.visualTemplates" }, dimension: "options", label: { fr: "Création de gabarits simples", en: "Simple template creation" }, when: { operator: "equals", value: "create-simple" }, operation: "add-range", rangeXof: { lower: 50_000, upper: 100_000 } },
  { id: "content-edit-rushes", input: { scope: "service-question", key: "content.videoLevel" }, dimension: "options", label: { fr: "Montage à partir de rushes fournis", en: "Editing supplied footage" }, when: { operator: "equals", value: "edit-client-rushes" }, operation: "add-range", rangeXof: { lower: 40_000, upper: 90_000 } },
  { id: "content-shoot-edit", input: { scope: "service-question", key: "content.videoLevel" }, dimension: "logistics", label: { fr: "Captation et montage", en: "Shoot and edit" }, when: { operator: "equals", value: "shoot-and-edit" }, operation: "add-range", rangeXof: { lower: 120_000, upper: 250_000 } },
  { id: "content-weekly-rhythm", input: { scope: "service-question", key: "content.deliveryRhythm" }, dimension: "duration", label: { fr: "Livraisons hebdomadaires", en: "Weekly delivery rhythm" }, when: { operator: "equals", value: "weekly" }, operation: "add-range", rangeXof: { lower: 20_000, upper: 40_000 } },
  { id: "content-monthly-rhythm", input: { scope: "service-question", key: "content.deliveryRhythm" }, dimension: "duration", label: { fr: "Livraisons mensuelles", en: "Monthly delivery rhythm" }, when: { operator: "equals", value: "monthly" }, operation: "add-range", rangeXof: { lower: 40_000, upper: 80_000 } },
  { id: "content-campaign-rhythm", input: { scope: "service-question", key: "content.deliveryRhythm" }, dimension: "duration", label: { fr: "Livraisons par jalons de campagne", en: "Campaign milestone delivery" }, when: { operator: "equals", value: "campaign-milestones" }, operation: "add-range", rangeXof: { lower: 30_000, upper: 60_000 } },
  { id: "content-paid-rights", input: { scope: "service-question", key: "content.usageRights" }, dimension: "rights", label: { fr: "Usages publicitaires", en: "Paid-media usage" }, when: { operator: "includes", value: "paid" }, operation: "add-range", rangeXof: { lower: 20_000, upper: 50_000 } },
  { id: "content-extended-rights", input: { scope: "service-question", key: "content.usageRights" }, dimension: "rights", label: { fr: "Territoires d’usage étendus", en: "Extended usage territories" }, when: { operator: "includes", value: "extended-territories" }, operation: "add-range", rangeXof: { lower: 40_000, upper: 90_000 } },
  { id: "content-local-production", input: { scope: "service-question", key: "content.onSiteProduction" }, dimension: "logistics", label: { fr: "Production locale sur site", en: "Local on-site production" }, when: { operator: "equals", value: "local" }, operation: "add-range", rangeXof: { lower: 80_000, upper: 160_000 } },
  { id: "content-multiple-local-production", input: { scope: "service-question", key: "content.onSiteProduction" }, dimension: "logistics", label: { fr: "Plusieurs productions locales", en: "Multiple local productions" }, when: { operator: "equals", value: "multiple-local" }, operation: "add-range", rangeXof: { lower: 160_000, upper: 300_000 } },
  ...contextRules("content"),
];

const auditRules: PricingRule[] = [
  { id: "audit-assets-four-six", input: { scope: "service-question", key: "audit.assetCount" }, dimension: "volume", label: { fr: "Quatre à six éléments à examiner", en: "Four to six items to review" }, when: { operator: "equals", value: "four-six" }, operation: "add-range", rangeXof: { lower: 30_000, upper: 60_000 } },
  { id: "audit-assets-seven-twelve", input: { scope: "service-question", key: "audit.assetCount" }, dimension: "volume", label: { fr: "Sept à douze éléments à examiner", en: "Seven to twelve items to review" }, when: { operator: "equals", value: "seven-twelve" }, operation: "add-range", rangeXof: { lower: 90_000, upper: 180_000 } },
  { id: "audit-assets-thirteen-plus", input: { scope: "service-question", key: "audit.assetCount" }, dimension: "volume", label: { fr: "Plus de douze éléments à examiner", en: "More than twelve items to review" }, when: { operator: "equals", value: "thirteen-plus" }, operation: "add-range", rangeXof: { lower: 180_000, upper: 360_000 } },
  { id: "audit-brands-two-three", input: { scope: "service-question", key: "audit.brandCount" }, dimension: "volume", label: { fr: "Deux à trois marques ou activités", en: "Two to three brands or activities" }, when: { operator: "equals", value: "two-three" }, operation: "add-range", rangeXof: { lower: 45_000, upper: 80_000 } },
  { id: "audit-brands-four-plus", input: { scope: "service-question", key: "audit.brandCount" }, dimension: "volume", label: { fr: "Quatre marques ou activités ou plus", en: "Four or more brands or activities" }, when: { operator: "equals", value: "four-plus" }, operation: "add-range", rangeXof: { lower: 135_000, upper: 240_000 } },
  { id: "audit-deep", input: { scope: "service-question", key: "audit.depth" }, dimension: "complexity", label: { fr: "Audit approfondi", en: "Deep audit" }, when: { operator: "equals", value: "deep-audit" }, operation: "add-range", rangeXof: { lower: 80_000, upper: 140_000 } },
  { id: "audit-roadmap", input: { scope: "service-question", key: "audit.depth" }, dimension: "complexity", label: { fr: "Feuille de route priorisée", en: "Prioritised roadmap" }, when: { operator: "equals", value: "roadmap" }, operation: "add-range", rangeXof: { lower: 50_000, upper: 100_000 } },
  { id: "audit-presentation", input: { scope: "service-question", key: "audit.depth" }, dimension: "complexity", label: { fr: "Audit préparé pour une restitution d’équipe", en: "Audit prepared for a team presentation" }, when: { operator: "equals", value: "presentation" }, operation: "add-range", rangeXof: { lower: 170_000, upper: 320_000 } },
  { id: "audit-implementation", input: { scope: "service-question", key: "audit.depth" }, dimension: "complexity", label: { fr: "Audit avec accompagnement à la mise en œuvre", en: "Audit with implementation support" }, when: { operator: "equals", value: "implementation" }, operation: "add-range", rangeXof: { lower: 305_000, upper: 590_000 } },
  { id: "audit-focused-benchmark", input: { scope: "service-question", key: "audit.benchmarkScope" }, dimension: "options", label: { fr: "Benchmark ciblé", en: "Focused benchmark" }, when: { operator: "equals", value: "focused" }, operation: "add-range", rangeXof: { lower: 25_000, upper: 45_000 } },
  { id: "audit-extended-benchmark", input: { scope: "service-question", key: "audit.benchmarkScope" }, dimension: "options", label: { fr: "Benchmark étendu", en: "Extended benchmark" }, when: { operator: "equals", value: "extended" }, operation: "add-range", rangeXof: { lower: 60_000, upper: 110_000 } },
  { id: "audit-exports", input: { scope: "service-question", key: "audit.dataAccess" }, dimension: "options", label: { fr: "Analyse d’exports", en: "Export analysis" }, when: { operator: "includes", value: "exports" }, operation: "add-range", rangeXof: { lower: 20_000, upper: 40_000 } },
  { id: "audit-analytics", input: { scope: "service-question", key: "audit.dataAccess" }, dimension: "options", label: { fr: "Analyse des données analytics", en: "Analytics review" }, when: { operator: "includes", value: "analytics" }, operation: "add-range", rangeXof: { lower: 30_000, upper: 60_000 } },
  ...contextRules("audit"),
];

const identityRules: PricingRule[] = [
  { id: "identity-complete", input: { scope: "service-question", key: "identity.projectType" }, dimension: "complexity", label: { fr: "Identité visuelle complète", en: "Complete visual identity" }, when: { operator: "equals", value: "complete-identity" }, operation: "add-range", rangeXof: { lower: 80_000, upper: 140_000 } },
  { id: "identity-guidelines-only", input: { scope: "service-question", key: "identity.projectType" }, dimension: "complexity", label: { fr: "Formalisation de charte", en: "Guidelines formalisation" }, when: { operator: "equals", value: "guidelines" }, operation: "add-range", rangeXof: { lower: 60_000, upper: 120_000 } },
  { id: "identity-refresh", input: { scope: "service-question", key: "identity.projectType" }, dimension: "complexity", label: { fr: "Rafraîchissement d’identité", en: "Identity refresh" }, when: { operator: "equals", value: "refresh" }, operation: "add-range", rangeXof: { lower: 80_000, upper: 160_000 } },
  { id: "identity-assets", input: { scope: "service-question", key: "identity.projectType" }, dimension: "complexity", label: { fr: "Déclinaisons d’une identité existante", en: "Existing-identity asset production" }, when: { operator: "equals", value: "assets" }, operation: "add-range", rangeXof: { lower: 50_000, upper: 100_000 } },
  { id: "identity-no-visual-base", input: { scope: "service-question", key: "identity.visualState" }, dimension: "complexity", label: { fr: "Construction depuis une page blanche", en: "Building from a blank slate" }, when: { operator: "includes", value: "none" }, operation: "add-range", rangeXof: { lower: 20_000, upper: 40_000 } },
  { id: "identity-naming-shortlist", input: { scope: "service-question", key: "identity.namingState" }, dimension: "options", label: { fr: "Clarification d’une shortlist de noms", en: "Naming shortlist clarification" }, when: { operator: "equals", value: "shortlist" }, operation: "add-range", rangeXof: { lower: 30_000, upper: 60_000 } },
  { id: "identity-positioning-partial", input: { scope: "service-question", key: "identity.positioningState" }, dimension: "complexity", label: { fr: "Clarification du positionnement", en: "Positioning clarification" }, when: { operator: "equals", value: "partial" }, operation: "add-range", rangeXof: { lower: 40_000, upper: 80_000 } },
  { id: "identity-positioning-framing", input: { scope: "service-question", key: "identity.positioningState" }, dimension: "complexity", label: { fr: "Cadrage stratégique du positionnement", en: "Strategic positioning framing" }, when: { operator: "equals", value: "needs-framing" }, operation: "add-range", rangeXof: { lower: 50_000, upper: 90_000 } },
  { id: "identity-brands-two-three", input: { scope: "service-question", key: "identity.brandCount" }, dimension: "volume", label: { fr: "Deux à trois marques ou gammes", en: "Two to three brands or ranges" }, when: { operator: "equals", value: "two-three" }, operation: "add-range", rangeXof: { lower: 100_000, upper: 180_000 } },
  { id: "identity-brands-four-plus", input: { scope: "service-question", key: "identity.brandCount" }, dimension: "volume", label: { fr: "Quatre marques ou gammes ou plus", en: "Four or more brands or ranges" }, when: { operator: "equals", value: "four-plus" }, operation: "add-range", rangeXof: { lower: 300_000, upper: 540_000 } },
  { id: "identity-logo-variants", input: { scope: "service-question", key: "identity.coreDeliverables" }, dimension: "options", label: { fr: "Variantes de logo", en: "Logo variants" }, when: { operator: "includes", value: "logo-variants" }, operation: "add-range", rangeXof: { lower: 10_000, upper: 25_000 } },
  { id: "identity-graphic-elements", input: { scope: "service-question", key: "identity.coreDeliverables" }, dimension: "options", label: { fr: "Éléments graphiques", en: "Graphic elements" }, when: { operator: "includes", value: "graphic-elements" }, operation: "add-range", rangeXof: { lower: 25_000, upper: 50_000 } },
  { id: "identity-art-direction", input: { scope: "service-question", key: "identity.coreDeliverables" }, dimension: "options", label: { fr: "Direction artistique", en: "Art direction" }, when: { operator: "includes", value: "art-direction" }, operation: "add-range", rangeXof: { lower: 30_000, upper: 60_000 } },
  { id: "identity-social-kit", input: { scope: "service-question", key: "identity.coreDeliverables" }, dimension: "options", label: { fr: "Kit réseaux sociaux", en: "Social-media kit" }, when: { operator: "includes", value: "social-kit" }, operation: "add-range", rangeXof: { lower: 25_000, upper: 50_000 } },
  { id: "identity-compact-guide", input: { scope: "service-question", key: "identity.coreDeliverables" }, dimension: "options", label: { fr: "Guide simple d’utilisation", en: "Simple usage guide" }, when: { operator: "includes", value: "guide-compact" }, operation: "add-range", rangeXof: { lower: 40_000, upper: 70_000 } },
  { id: "identity-detailed-guide", input: { scope: "service-question", key: "identity.coreDeliverables" }, dimension: "options", label: { fr: "Guide détaillé", en: "Detailed guide" }, when: { operator: "includes", value: "guide-detailed" }, operation: "add-range", rangeXof: { lower: 120_000, upper: 220_000 } },
  { id: "identity-icons", input: { scope: "service-question", key: "identity.coreDeliverables" }, dimension: "options", label: { fr: "Iconographie sur mesure", en: "Custom iconography" }, when: { operator: "includes", value: "icons" }, operation: "add-range", rangeXof: { lower: 40_000, upper: 90_000 } },
  { id: "identity-illustrations", input: { scope: "service-question", key: "identity.coreDeliverables" }, dimension: "options", label: { fr: "Illustrations sur mesure", en: "Custom illustrations" }, when: { operator: "includes", value: "illustrations" }, operation: "add-range", rangeXof: { lower: 70_000, upper: 150_000 } },
  { id: "identity-motion", input: { scope: "service-question", key: "identity.coreDeliverables" }, dimension: "options", label: { fr: "Éléments d’identité animés", en: "Animated identity elements" }, when: { operator: "includes", value: "motion" }, operation: "add-range", rangeXof: { lower: 90_000, upper: 180_000 } },
  { id: "identity-complete-kit", input: { scope: "service-question", key: "identity.coreDeliverables" }, dimension: "options", label: { fr: "Kit complet de déploiement", en: "Complete rollout kit" }, when: { operator: "includes", value: "complete-kit" }, operation: "add-range", rangeXof: { lower: 200_000, upper: 350_000 } },
  { id: "identity-recommended-kit", input: { scope: "service-question", key: "identity.coreDeliverables" }, dimension: "options", label: { fr: "Kit recommandé à cadrer", en: "Recommended kit to be framed" }, when: { operator: "includes", value: "recommended" }, operation: "add-range", rangeXof: { lower: 100_000, upper: 180_000 } },
  { id: "identity-supports-three-five", input: { scope: "service-question", key: "identity.supportCount" }, dimension: "volume", label: { fr: "Trois à cinq supports", en: "Three to five assets" }, when: { operator: "equals", value: "three-five" }, operation: "add-range", rangeXof: { lower: 60_000, upper: 135_000 } },
  { id: "identity-supports-six-plus", input: { scope: "service-question", key: "identity.supportCount" }, dimension: "volume", label: { fr: "Six supports ou plus", en: "Six assets or more" }, when: { operator: "equals", value: "six-plus" }, operation: "add-range", rangeXof: { lower: 80_000, upper: 180_000 } },
  { id: "identity-commercial-docs", input: { scope: "service-question", key: "identity.priorityUses" }, dimension: "options", label: { fr: "Usages sur documents commerciaux", en: "Commercial-document use" }, when: { operator: "includes", value: "commercial-docs" }, operation: "add-range", rangeXof: { lower: 15_000, upper: 30_000 } },
  { id: "identity-event", input: { scope: "service-question", key: "identity.priorityUses" }, dimension: "options", label: { fr: "Usages événementiels", en: "Event use" }, when: { operator: "includes", value: "event" }, operation: "add-range", rangeXof: { lower: 30_000, upper: 70_000 } },
  { id: "identity-signage", input: { scope: "service-question", key: "identity.priorityUses" }, dimension: "options", label: { fr: "Signalétique", en: "Signage" }, when: { operator: "includes", value: "signage" }, operation: "add-range", rangeXof: { lower: 50_000, upper: 100_000 } },
  { id: "identity-packaging", input: { scope: "service-question", key: "identity.priorityUses" }, dimension: "options", label: { fr: "Packaging", en: "Packaging" }, when: { operator: "includes", value: "packaging" }, operation: "add-range", rangeXof: { lower: 50_000, upper: 100_000 } },
  { id: "identity-print-production", input: { scope: "service-question", key: "identity.priorityUses" }, dimension: "options", label: { fr: "Préparation des fichiers pour impression", en: "Print production file preparation" }, when: { operator: "includes", value: "print" }, operation: "add-range", rangeXof: { lower: 20_000, upper: 50_000 } },
  ...contextRules("identity"),
];

/**
 * Working calibration proposed from Beninese and regional market references,
 * Carole's intermediate positioning and the real CLOGIS scope. Amounts remain
 * versioned here so future adjustments never rewrite a historical estimate.
 */
export const productionPricingCatalog = {
  modelVersion: "2026-07-15-benin-calibration",
  status: "active",
  effectiveFrom: "2026-07-15",
  services: {
    "editorial-strategy": { status: "configured", baseRangeXof: { lower: 150_000, upper: 260_000 }, rules: editorialRules },
    "digital-communication": { status: "configured", baseRangeXof: { lower: 100_000, upper: 180_000 }, rules: communicationRules },
    "content-creation": { status: "configured", baseRangeXof: { lower: 100_000, upper: 180_000 }, rules: contentRules },
    "audit-advice": { status: "configured", baseRangeXof: { lower: 100_000, upper: 200_000 }, rules: auditRules },
    "visual-identity": { status: "configured", baseRangeXof: { lower: 120_000, upper: 200_000 }, rules: identityRules },
  },
  mutualizationRules: [
    {
      id: "editorial-content-shared-discovery",
      label: { fr: "Cadrage mutualisé entre stratégie et contenus", en: "Shared discovery for strategy and content" },
      requiredServiceIds: ["editorial-strategy", "content-creation"],
      appliedToServiceIds: ["content-creation"],
      discountBasisPoints: 600,
    },
    {
      id: "communication-content-shared-planning",
      label: { fr: "Planification mutualisée entre pilotage et contenus", en: "Shared planning for communication and content" },
      requiredServiceIds: ["digital-communication", "content-creation"],
      appliedToServiceIds: ["content-creation"],
      discountBasisPoints: 800,
    },
    {
      id: "editorial-communication-shared-framing",
      label: { fr: "Cadrage mutualisé entre stratégie et pilotage", en: "Shared framing for strategy and communication" },
      requiredServiceIds: ["editorial-strategy", "digital-communication"],
      appliedToServiceIds: ["digital-communication"],
      discountBasisPoints: 500,
    },
  ],
  rounding: {
    status: "configured",
    incrementXof: 5_000,
    lower: "down",
    upper: "up",
  },
  tax: {
    status: "configured",
    treatment: "not-applicable",
    rateBasisPoints: 0,
    label: { fr: "Fiscalité non calculée", en: "Tax not calculated" },
  },
  questionnaireContract: getSerializableQuestionnaireContract(),
} as const satisfies PricingCatalog;

/**
 * Frozen official rate snapshot. The USD reference is the latest BCEAO rate
 * found and verified on 2026-07-15; an estimate stores this snapshot rather
 * than re-reading a mutable live rate.
 */
export const officialExchangeRateSnapshot = {
  snapshotId: "bceao-2026-07-13-retrieved-2026-07-15",
  retrievedAt: "2026-07-15T00:00:00+01:00",
  rates: {
    XOF: {
      xofPerUnit: 1,
      rateDate: "2026-07-15",
      sourceName: "Montant canonique XOF",
      sourceUrl: "https://www.bceao.int/fr/content/histoire-du-franc-cfa",
      displayDecimals: 0,
    },
    EUR: {
      xofPerUnit: 655.957,
      rateDate: "1999-01-01",
      sourceName: "Parité fixe BCEAO EUR/XOF",
      sourceUrl: "https://www.bceao.int/fr/content/histoire-du-franc-cfa",
      displayDecimals: 0,
    },
    USD: {
      xofPerUnit: 574.19,
      rateDate: "2026-07-13",
      sourceName: "Cours de référence BCEAO USD/XOF",
      sourceUrl: "https://www.bceao.int/fr/cours/cours-de-reference-des-principales-devises-contre-Franc-CFA",
      displayDecimals: 0,
    },
  },
} as const satisfies ExchangeRateSnapshot;

export const missingPricingDecisions = {
  services: [],
  mutualization: [],
  rounding: [],
  tax: ["Confirmer le régime fiscal réel de Carole avant d’ajouter la TVA au calcul public"],
} as const;
