import {
  isClientBriefFieldVisible,
  type ClientBriefTemplate,
  type ClientBriefValue,
} from "../../../shared/client-brief-contract.js";

type DemoLocale = "fr" | "en";
type DemoAnswers = Record<string, ClientBriefValue>;
type LocalizedDemo = Record<DemoLocale, DemoAnswers>;

const editorialStrategy: LocalizedDemo = {
  fr: {
    projectName: "Sika Marché",
    activity: "Sika Marché est une place de marché en ligne qui aide des artisanes béninoises à vendre leurs produits au Bénin et dans la sous-région.",
    projectTrigger: "Nos publications sont régulières, mais elles présentent surtout les produits. Nous voulons mieux raconter le savoir-faire des artisanes avant notre ouverture au Togo.",
    primaryAudience: "Des femmes et hommes de 25 à 45 ans, sensibles au fait-main local, qui hésitent encore à commander en ligne par manque de confiance sur la qualité et la livraison.",
    businessObjective: "Augmenter les commandes issues des contenus et faire de Sika Marché une référence du fait-main béninois.",
    organizationType: "business",
    projectStage: "active",
    marketScope: "regional",
    timeline: "one-two-months",
    currentState: "revision",
    existingStrategyIssues: "Nous avons un calendrier mensuel, mais les sujets se répètent, le ton change selon la personne qui publie et les contenus ne répondent pas clairement aux craintes sur la livraison.",
    desiredOutcome: "Le public doit comprendre qui fabrique les produits, reconnaître leur qualité et se sentir suffisamment rassuré pour commander.",
    editorialRisks: "Sans changement, la marque restera perçue comme un simple catalogue et l'ouverture au Togo risque de ne pas créer d'intérêt durable.",
    audienceNeeds: "Les acheteurs de Cotonou veulent voir les finitions et connaître les délais. La diaspora cherche des cadeaux authentiques faciles à envoyer. Ces constats viennent des messages Instagram et des appels du service client.",
    channels: ["instagram", "facebook", "newsletter"],
    existingEvidence: "Douze mois de publications, les statistiques Instagram, les questions reçues par WhatsApp, les avis après achat et les chiffres de vente par collection.",
    evidenceConfidence: "3",
    representativeContent: "https://example.com/sika-marche/campagne-artisanes",
    editorialMission: "Nous aidons les amateurs de créations locales à acheter en confiance grâce à des histoires transparentes sur les artisanes, les matières et la fabrication.",
    contentPillars: "Portraits d'artisanes avec preuves de savoir-faire ; coulisses de fabrication ; conseils d'entretien ; idées cadeaux ; informations claires sur la commande et la livraison.",
    voice: "Nous sommes chaleureux, précis et fiers du savoir-faire local, mais pas folkloriques, excessifs ni culpabilisants.",
    forbiddenTopics: "Ne pas promettre une livraison le jour même, ne pas employer le mot « luxe » sans preuve et ne pas parler au nom des artisanes sans leur accord.",
    deliverables: "Une plateforme éditoriale claire, quatre piliers de contenu, un guide de ton, une matrice de sujets et un modèle de calendrier utilisable chaque mois.",
    channelCadence: "Instagram : trois publications par semaine pour la découverte. Facebook : deux publications par semaine pour rassurer. Newsletter : deux envois par mois pour les nouveautés et les histoires longues.",
    handoffSupport: "Un atelier de prise en main avec la chargée de contenu et une relecture du premier calendrier mensuel.",
    projectLead: "Aïcha Dossou — Responsable marketing — aicha.dossou@example.com",
    finalDecisionMaker: "Nadia Kora — Fondatrice",
    contributors: "La responsable e-commerce fournit les données de vente ; deux artisanes référentes valident les informations sur la fabrication.",
    validationProcess: "one",
    feedbackProcess: "Aïcha regroupe les retours dans un document partagé sous deux jours ouvrés.",
    confidentiality: "Les marges et les coordonnées personnelles des artisanes ne doivent pas apparaître dans les documents partagés.",
    successCriteria: "L'équipe peut préparer un mois de contenus sans improviser le ton, chaque sujet est relié à un besoin du public et la direction sait quoi mesurer.",
    outOfScope: "La production des photos, la publication quotidienne et l'achat publicitaire ne font pas partie de cette mission.",
    openQuestions: "Valider les marchés prioritaires au Togo et choisir les artisanes disponibles pour les premiers portraits.",
  },
  en: {
    projectName: "Sika Market",
    activity: "Sika Market is an online marketplace helping Beninese craftswomen sell their products in Benin and across West Africa.",
    projectTrigger: "We publish regularly, but most posts only show products. Before expanding to Togo, we want to tell stronger stories about the makers and their craft.",
    primaryAudience: "Women and men aged 25 to 45 who value locally made goods but still hesitate to order online because they are unsure about quality and delivery.",
    businessObjective: "Increase orders generated by content and establish Sika Market as a trusted name for Beninese craftsmanship.",
    organizationType: "business",
    projectStage: "active",
    marketScope: "regional",
    timeline: "one-two-months",
    currentState: "revision",
    existingStrategyIssues: "We have a monthly calendar, but topics repeat, the tone changes depending on who posts, and our content does not clearly address delivery concerns.",
    desiredOutcome: "People should understand who makes the products, recognise their quality and feel confident enough to order.",
    editorialRisks: "Without change, the brand will remain a simple catalogue and our expansion to Togo may fail to build lasting interest.",
    audienceNeeds: "Cotonou buyers want to see finishes and understand delivery times. The diaspora wants authentic gifts that are easy to ship. We hear this in Instagram messages and customer calls.",
    channels: ["instagram", "facebook", "newsletter"],
    existingEvidence: "Twelve months of posts, Instagram insights, questions received on WhatsApp, post-purchase reviews and sales by collection.",
    evidenceConfidence: "3",
    representativeContent: "https://example.com/sika-market/makers-campaign",
    editorialMission: "We help people who value local craft buy with confidence through transparent stories about makers, materials and production.",
    contentPillars: "Maker profiles with proof of craft; behind-the-scenes production; care advice; gift ideas; clear ordering and delivery information.",
    voice: "We are warm, precise and proud of local craft, but never folkloric, exaggerated or guilt-inducing.",
    forbiddenTopics: "Do not promise same-day delivery, use the word luxury without proof or speak on behalf of a maker without her approval.",
    deliverables: "A clear editorial platform, four content pillars, a tone guide, a topic matrix and a reusable monthly calendar template.",
    channelCadence: "Instagram: three discovery posts per week. Facebook: two reassuring posts per week. Newsletter: two monthly sends for launches and longer stories.",
    handoffSupport: "One handover workshop with the content manager and a review of the first monthly calendar.",
    projectLead: "Aïcha Dossou — Marketing manager — aicha.dossou@example.com",
    finalDecisionMaker: "Nadia Kora — Founder",
    contributors: "The e-commerce manager provides sales data; two maker representatives validate production information.",
    validationProcess: "one",
    feedbackProcess: "Aïcha consolidates feedback in one shared document within two business days.",
    confidentiality: "Margins and the makers' personal contact details must not appear in shared documents.",
    successCriteria: "The team can plan one month of content without improvising the tone, every topic connects to an audience need and management knows what to measure.",
    outOfScope: "Photography production, daily publishing and paid media buying are outside this engagement.",
    openQuestions: "Confirm the priority markets in Togo and identify the makers available for the first profiles.",
  },
};

const digitalCommunication: LocalizedDemo = {
  fr: {
    projectName: "Mémora",
    activity: "Mémora propose à Cotonou un service de livraison de repas sains préparés chaque semaine pour les personnes qui travaillent.",
    projectTrigger: "Nous lançons une formule d'abonnement dans six semaines et voulons transformer notre audience Instagram en premiers abonnés.",
    primaryAudience: "Des actifs de 25 à 40 ans qui manquent de temps le midi, souhaitent mieux manger et craignent qu'un abonnement soit trop rigide.",
    businessObjective: "Obtenir 120 demandes qualifiées et convertir au moins 40 personnes en abonnés pendant le lancement.",
    organizationType: "business",
    projectStage: "launch",
    marketScope: "local",
    timeline: "one-two-months",
    engagementType: "campaign",
    primaryGoal: "leads",
    message: "Des déjeuners équilibrés livrés au bureau sans engagement long. Les menus et les prix sont visibles avant l'inscription ; l'appel à l'action est de demander une semaine d'essai.",
    toneRestrictions: "Ton simple, énergique et rassurant. Éviter les promesses médicales, les discours culpabilisants sur le poids et le jargon nutritionnel.",
    channels: ["instagram", "facebook", "website"],
    accounts: "Instagram @memora.bj et Facebook Mémora sont administrés par l'équipe. La page d'inscription sera hébergée sur memora.example.com ; les accès seront transmis séparément.",
    operationalTasks: "Plan de campagne, calendrier, textes, coordination des visuels, programmation des publications, réponses aux questions courantes et bilan hebdomadaire.",
    excludedTasks: "La prise de vue culinaire, le développement de la page d'inscription et la gestion des livraisons restent à la charge de Mémora.",
    campaigns: "Pré-lancement pendant deux semaines, ouverture des essais pendant trois semaines, puis rappel final. Destination : formulaire d'essai. L'équipe fournit menus, prix, photos et conditions.",
    communityManagementLevel: "standard",
    moderation: "Réponse du lundi au samedi entre 9 h et 18 h sous une journée. Les questions sur les allergies sont transmises à la responsable cuisine.",
    responseCoverage: "2",
    paidMedia: "strategy",
    paidMediaDetails: "Campagne Meta ciblée sur Cotonou, budget de diffusion validé séparément. L'équipe Mémora paie directement la plateforme.",
    measurement: "Indicateur principal : formulaires d'essai complétés. Référence actuelle : 15 demandes mensuelles. Cible : 120 demandes sur la campagne. Source : formulaire et tableau de suivi hebdomadaire.",
    projectLead: "Mireille Ahouansou — Responsable commerciale — mireille.ahouansou@example.com",
    finalDecisionMaker: "Sébastien Houngbédji — Cofondateur",
    contributors: "La cheffe valide les informations nutritionnelles ; le photographe livre les images avant le lancement.",
    validationProcess: "one",
    feedbackProcess: "Mireille centralise les retours de l'équipe dans un document unique le lendemain de chaque présentation.",
    confidentiality: "Les données personnelles des prospects et les recettes détaillées restent internes.",
    successCriteria: "La campagne est publiée aux dates prévues, les messages courants reçoivent une réponse cohérente et le tableau permet de relier chaque demande à son canal.",
    outOfScope: "Refonte du site, shooting photo, production vidéo longue et gestion du service de livraison.",
    openQuestions: "Confirmer le budget Meta, la date de disponibilité des photos et la capacité maximale d'abonnements pour la première semaine.",
  },
  en: {
    projectName: "Memora",
    activity: "Memora delivers healthy weekly meals in Cotonou for people who work away from home.",
    projectTrigger: "We are launching a subscription plan in six weeks and want to convert our Instagram audience into the first subscribers.",
    primaryAudience: "Professionals aged 25 to 40 who lack time at lunch, want to eat better and worry that a subscription may be too restrictive.",
    businessObjective: "Generate 120 qualified enquiries and convert at least 40 people into subscribers during the launch.",
    organizationType: "business",
    projectStage: "launch",
    marketScope: "local",
    timeline: "one-two-months",
    engagementType: "campaign",
    primaryGoal: "leads",
    message: "Balanced lunches delivered to the office without a long commitment. Menus and prices are visible before sign-up; the call to action is to request a trial week.",
    toneRestrictions: "Simple, energetic and reassuring. Avoid medical claims, guilt about weight and nutrition jargon.",
    channels: ["instagram", "facebook", "website"],
    accounts: "Instagram @memora.bj and the Memora Facebook page are owned by the team. The sign-up page will be hosted on memora.example.com; credentials will be shared separately.",
    operationalTasks: "Campaign plan, calendar, copy, visual coordination, publishing, replies to common questions and a weekly performance summary.",
    excludedTasks: "Food photography, sign-up page development and delivery operations remain Memora's responsibility.",
    campaigns: "Two weeks of pre-launch, three weeks of trial enrolment and a final reminder. Destination: the trial form. The team supplies menus, prices, photos and terms.",
    communityManagementLevel: "standard",
    moderation: "Reply Monday to Saturday, 9 am to 6 pm, within one day. Allergy questions are escalated to the kitchen manager.",
    responseCoverage: "2",
    paidMedia: "strategy",
    paidMediaDetails: "A Meta campaign targeted to Cotonou with a separately approved media budget. Memora pays the platform directly.",
    measurement: "Primary measure: completed trial forms. Current baseline: 15 monthly enquiries. Target: 120 during the campaign. Source: the form and a weekly tracking sheet.",
    projectLead: "Mireille Ahouansou — Sales manager — mireille.ahouansou@example.com",
    finalDecisionMaker: "Sébastien Houngbédji — Co-founder",
    contributors: "The chef validates nutrition information; the photographer supplies images before launch.",
    validationProcess: "one",
    feedbackProcess: "Mireille consolidates team feedback in one document on the day after each presentation.",
    confidentiality: "Prospects' personal data and detailed recipes remain internal.",
    successCriteria: "The campaign is published on schedule, common questions receive consistent answers and the tracking sheet links every enquiry to its source channel.",
    outOfScope: "Website redesign, photography, long-form video production and delivery management.",
    openQuestions: "Confirm the Meta budget, the photo delivery date and maximum subscription capacity for the first week.",
  },
};

const contentCreation: LocalizedDemo = {
  fr: {
    projectName: "Atelier Nôvi",
    activity: "Atelier Nôvi conçoit du mobilier contemporain fabriqué à Cotonou pour les particuliers, restaurants et petits hôtels.",
    projectTrigger: "Une nouvelle collection sort dans deux mois et nous n'avons pas encore de contenus capables d'expliquer les matières, le travail artisanal et les possibilités de personnalisation.",
    primaryAudience: "Des propriétaires et responsables d'établissements de 30 à 50 ans qui cherchent des pièces durables mais veulent être rassurés sur les délais et l'entretien.",
    businessObjective: "Créer une bibliothèque de contenus pour lancer la collection et générer des demandes de rendez-vous au showroom.",
    organizationType: "business",
    projectStage: "active",
    marketScope: "national",
    timeline: "one-two-months",
    contentPurpose: "Présenter six pièces, montrer leur fabrication et donner au public assez d'informations pour demander un devis ou visiter le showroom.",
    contentFormats: ["article", "carousel", "short-video"],
    writingDetails: "Six fiches narratives de 500 à 700 mots et un article sur le choix du bois local, dans un ton accessible et précis.",
    visualDetails: "Deux carrousels par pièce : détails de fabrication et conseils d'usage, aux formats Instagram et LinkedIn.",
    videoDetails: "Six vidéos verticales de 30 à 45 secondes, avec gestes d'atelier, sous-titres et une courte intervention du designer.",
    cta: "Prendre rendez-vous au showroom ou demander les dimensions et finitions disponibles sur WhatsApp.",
    sourceMaterial: "Plans des meubles, notes du designer, liste des essences de bois, tarifs, photos de prototypes et disponibilité de deux artisans pour des entretiens.",
    factChecking: "Le designer valide les dimensions et les choix créatifs ; la responsable d'atelier confirme les matières et les délais de fabrication.",
    creativeDirection: "Une image sobre, lumineuse et tactile. Montrer les mains, les textures et les usages réels plutôt que des mises en scène luxueuses.",
    brandGuide: "https://example.com/atelier-novi/guide-de-marque",
    productionMode: "mixed",
    productionPlan: "Une demi-journée de préparation à distance, deux jours de tournage à l'atelier et une journée au showroom. Les textes sont préparés à partir des entretiens.",
    onSiteLogistics: "Atelier accessible de 8 h à 17 h, prises électriques disponibles, bruit des machines à anticiper. Le showroom peut être fermé au public une matinée.",
    variants: "Versions 9:16 sous-titrées pour Instagram, extraits 1:1 pour Facebook et visuels fixes sans texte pour le site.",
    productionReadiness: "4",
    usageRights: "Utilisation organique sur les réseaux, le site et les supports commerciaux au Bénin pendant trois ans. Toute campagne payante sera validée séparément.",
    thirdPartyRights: "Les artisans participants signeront une autorisation d'image. La musique devra provenir d'une bibliothèque sous licence incluse dans la production.",
    accessibility: "Sous-titres en français, contraste lisible, texte alternatif pour les images du site et informations essentielles compréhensibles sans le son.",
    delivery: "MP4 1080 x 1920, JPG haute définition, textes dans un document partagé et fichiers sources vidéo conservés six mois.",
    projectLead: "Clarisse Hountondji — Responsable de collection — clarisse.hountondji@example.com",
    finalDecisionMaker: "Armand Zinsou — Directeur créatif",
    contributors: "La responsable d'atelier organise les artisans ; le webmaster intègre les textes et images sur le site.",
    validationProcess: "one",
    feedbackProcess: "Clarisse regroupe les corrections par lot de contenus dans un tableau partagé sous 48 heures.",
    confidentiality: "Les prix fournisseurs et les plans techniques détaillés ne doivent pas être diffusés.",
    successCriteria: "Les six pièces disposent chacune d'un texte, d'un carrousel et d'une vidéo validés, correctement nommés et prêts pour les canaux prévus.",
    outOfScope: "Gestion quotidienne des réseaux, achat publicitaire, impression du catalogue et photographie de toute l'ancienne collection.",
    openQuestions: "Choisir les deux artisans filmés, confirmer la disponibilité du showroom et valider la bibliothèque musicale.",
  },
  en: {
    projectName: "Atelier Novi",
    activity: "Atelier Novi designs contemporary furniture made in Cotonou for homes, restaurants and small hotels.",
    projectTrigger: "A new collection launches in two months and we do not yet have content explaining the materials, craftsmanship and custom options.",
    primaryAudience: "Homeowners and venue managers aged 30 to 50 who want durable pieces but need reassurance about lead times and care.",
    businessObjective: "Build a content library for the collection launch and generate showroom appointment requests.",
    organizationType: "business",
    projectStage: "active",
    marketScope: "national",
    timeline: "one-two-months",
    contentPurpose: "Present six pieces, show how they are made and give people enough information to request a quote or visit the showroom.",
    contentFormats: ["article", "carousel", "short-video"],
    writingDetails: "Six 500-to-700-word narrative product pages and one article about choosing local wood, written in an accessible and precise tone.",
    visualDetails: "Two carousels per piece: making details and practical use, adapted for Instagram and LinkedIn.",
    videoDetails: "Six 30-to-45-second vertical videos featuring workshop gestures, captions and a short contribution from the designer.",
    cta: "Book a showroom appointment or request available dimensions and finishes on WhatsApp.",
    sourceMaterial: "Furniture plans, designer notes, wood species list, prices, prototype photos and two craftspeople available for interviews.",
    factChecking: "The designer validates dimensions and creative choices; the workshop manager confirms materials and production times.",
    creativeDirection: "A restrained, bright and tactile look. Show hands, textures and real use rather than luxury staging.",
    brandGuide: "https://example.com/atelier-novi/brand-guide",
    productionMode: "mixed",
    productionPlan: "A remote half-day preparation, two filming days in the workshop and one day in the showroom. Copy is developed from interviews.",
    onSiteLogistics: "Workshop available from 8 am to 5 pm, power outlets on site and machine noise to plan around. The showroom can close to visitors for one morning.",
    variants: "Captioned 9:16 versions for Instagram, 1:1 excerpts for Facebook and clean stills without text for the website.",
    productionReadiness: "4",
    usageRights: "Organic use on social media, the website and sales materials in Benin for three years. Paid campaigns require separate approval.",
    thirdPartyRights: "Participating craftspeople will sign image releases. Music must come from a licensed library included in production.",
    accessibility: "French captions, readable contrast, alternative text for website images and essential information understandable without sound.",
    delivery: "1080 x 1920 MP4 files, high-resolution JPGs, copy in a shared document and video source files retained for six months.",
    projectLead: "Clarisse Hountondji — Collection manager — clarisse.hountondji@example.com",
    finalDecisionMaker: "Armand Zinsou — Creative director",
    contributors: "The workshop manager coordinates the makers; the webmaster integrates copy and images on the site.",
    validationProcess: "one",
    feedbackProcess: "Clarisse consolidates corrections by content batch in a shared tracker within 48 hours.",
    confidentiality: "Supplier prices and detailed technical plans must not be published.",
    successCriteria: "Each of the six pieces has an approved article, carousel and video, correctly named and ready for its intended channels.",
    outOfScope: "Daily social media management, media buying, catalogue printing and photography of the full previous collection.",
    openQuestions: "Choose the two craftspeople to film, confirm showroom availability and approve the music library.",
  },
};

const auditAdvice: LocalizedDemo = {
  fr: {
    projectName: "Clinique Horizon",
    activity: "Clinique Horizon est un centre de santé privé à Porto-Novo qui accueille des patients en consultation générale et en suivi maternel.",
    projectTrigger: "Les demandes de rendez-vous en ligne ont baissé depuis trois mois alors que le trafic du site reste stable. La direction veut comprendre le problème avant d'investir dans une refonte.",
    primaryAudience: "Des adultes et jeunes parents de Porto-Novo qui cherchent rapidement une information fiable sur les consultations, les horaires et la prise de rendez-vous.",
    businessObjective: "Identifier les obstacles dans le parcours numérique et prioriser les corrections qui peuvent augmenter les rendez-vous confirmés.",
    organizationType: "business",
    projectStage: "active",
    marketScope: "local",
    timeline: "one-two-months",
    observedProblem: "Le trafic est stable mais les formulaires complétés ont diminué d'environ 30 %. Plusieurs patients disent ne pas trouver les horaires ni savoir si leur demande a bien été reçue.",
    auditQuestion: "Quelles étapes du site et du suivi WhatsApp font abandonner les patients avant la confirmation d'un rendez-vous ?",
    expectedDecision: "La direction doit décider des corrections à lancer immédiatement et savoir si une refonte complète est réellement nécessaire.",
    previousAttempts: "Le bouton de rendez-vous a été déplacé sur la page d'accueil et un message automatique WhatsApp a été ajouté, sans mesure avant-après.",
    auditScope: "Site public, formulaire de rendez-vous, messages automatiques WhatsApp et parcours mobile sur les trois derniers mois. Le logiciel médical interne est exclu.",
    inventory: "Site vitrine clinic-horizon.example.com, formulaire Tally géré par l'accueil, compte WhatsApp Business et fiche Google Business Profile.",
    dataAccess: "Statistiques Matomo sur six mois, exports anonymisés du formulaire et journal des messages automatiques. Les accès seront fournis par la responsable informatique sans partager de mot de passe dans le brief.",
    sensitivity: "confidential",
    evidenceConfidence: "3",
    auditDepth: "roadmap",
    criteria: "Clarté des informations, facilité de prise de rendez-vous sur mobile, cohérence des messages, accessibilité et continuité entre formulaire et WhatsApp.",
    standards: "Charte interne de confidentialité, bonnes pratiques WCAG pour les interfaces et procédure d'accueil de la clinique.",
    samplingMethod: "Analyser toutes les pages du parcours de rendez-vous et un échantillon anonymisé de 80 demandes réparties sur trois mois.",
    benchmarkNeeded: "yes",
    benchmarkPeers: "Comparer deux cliniques locales pour les informations attendues et deux services internationaux reconnus uniquement pour les bonnes pratiques de parcours mobile.",
    knownLimits: "Aucun enregistrement de session antérieur et peu de retours structurés des patients ; l'audit ne pourra pas évaluer la qualité des consultations.",
    auditDeliverables: "Diagnostic illustré, liste des problèmes classés par impact, recommandations justifiées et feuille de route en trois horizons.",
    implementation: "La responsable informatique et le prestataire web appliqueront les corrections. Carole présentera les priorités et relira les changements critiques.",
    specialistReview: "yes",
    projectLead: "Estelle Kpadonou — Responsable communication — estelle.kpadonou@example.com",
    finalDecisionMaker: "Dr Léon Agossou — Directeur de la clinique",
    contributors: "La responsable informatique fournit les données ; l'accueil explique le traitement quotidien des demandes ; le prestataire web estime les corrections.",
    validationProcess: "one",
    feedbackProcess: "Estelle rassemble les remarques de la direction et de l'accueil dans un seul document sous trois jours.",
    confidentiality: "Aucun nom de patient, motif de consultation ou numéro de téléphone ne doit être transmis. Seules des données anonymisées seront analysées.",
    successCriteria: "Le rapport permet de distinguer les corrections rapides de la refonte, chaque recommandation est reliée à une observation et un responsable peut planifier les actions.",
    outOfScope: "Audit médical, sécurité du logiciel clinique, campagne publicitaire et mise en œuvre complète des recommandations.",
    openQuestions: "Confirmer la disponibilité des exports anonymisés et déterminer si un avis juridique est requis avant l'analyse des messages.",
  },
  en: {
    projectName: "Horizon Clinic",
    activity: "Horizon Clinic is a private healthcare centre in Porto-Novo providing general consultations and maternal care.",
    projectTrigger: "Online appointment requests have fallen for three months while website traffic remains stable. Management wants to understand why before funding a redesign.",
    primaryAudience: "Adults and young parents in Porto-Novo who need reliable information about consultations, opening times and appointments quickly.",
    businessObjective: "Identify obstacles in the digital journey and prioritise changes that can increase confirmed appointments.",
    organizationType: "business",
    projectStage: "active",
    marketScope: "local",
    timeline: "one-two-months",
    observedProblem: "Traffic is stable, but completed forms have fallen by roughly 30%. Several patients say they cannot find opening times or tell whether their request was received.",
    auditQuestion: "Which parts of the website and WhatsApp follow-up cause patients to abandon before an appointment is confirmed?",
    expectedDecision: "Management must decide which fixes to launch now and whether a full redesign is genuinely necessary.",
    previousAttempts: "The appointment button was moved on the home page and an automated WhatsApp reply was added, but no before-and-after measurement was planned.",
    auditScope: "Public website, appointment form, automated WhatsApp messages and the mobile journey over the past three months. The internal medical system is excluded.",
    inventory: "clinic-horizon.example.com website, Tally form managed by reception, WhatsApp Business account and Google Business Profile.",
    dataAccess: "Six months of Matomo analytics, anonymised form exports and automated message logs. The IT manager will provide access without placing passwords in the brief.",
    sensitivity: "confidential",
    evidenceConfidence: "3",
    auditDepth: "roadmap",
    criteria: "Information clarity, ease of booking on mobile, message consistency, accessibility and continuity between the form and WhatsApp.",
    standards: "Internal confidentiality policy, WCAG interface guidance and the clinic's reception procedure.",
    samplingMethod: "Review every page in the appointment journey and an anonymised sample of 80 requests spread across three months.",
    benchmarkNeeded: "yes",
    benchmarkPeers: "Compare two local clinics for expected information and two recognised international services solely for mobile journey practices.",
    knownLimits: "No historical session recordings and little structured patient feedback; the audit cannot assess the quality of medical consultations.",
    auditDeliverables: "Illustrated diagnostic, issues ranked by impact, evidence-based recommendations and a roadmap across three time horizons.",
    implementation: "The IT manager and web provider will implement changes. Carole will present priorities and review critical updates.",
    specialistReview: "yes",
    projectLead: "Estelle Kpadonou — Communications manager — estelle.kpadonou@example.com",
    finalDecisionMaker: "Dr Léon Agossou — Clinic director",
    contributors: "The IT manager provides data, reception explains daily request handling and the web provider estimates changes.",
    validationProcess: "one",
    feedbackProcess: "Estelle consolidates management and reception comments in one document within three days.",
    confidentiality: "No patient names, consultation reasons or phone numbers may be shared. Only anonymised data will be analysed.",
    successCriteria: "The report distinguishes quick fixes from redesign work, links every recommendation to an observation and gives owners enough detail to plan action.",
    outOfScope: "Medical audit, clinical software security, advertising and full implementation of recommendations.",
    openQuestions: "Confirm access to anonymised exports and determine whether legal review is required before message analysis.",
  },
};

const visualIdentity: LocalizedDemo = {
  fr: {
    projectName: "Orí Voyages",
    activity: "Orí Voyages conçoit des séjours culturels en petits groupes au Bénin pour la diaspora et les voyageurs francophones.",
    projectTrigger: "L'agence ouvre ses premières ventes dans trois mois et a besoin d'une identité capable d'inspirer confiance avant la mise en ligne du site.",
    primaryAudience: "Des voyageurs de 30 à 55 ans vivant en Europe ou en Afrique de l'Ouest, qui veulent une expérience culturelle sérieuse sans parcours touristique impersonnel.",
    businessObjective: "Lancer la marque avec une image distinctive et cohérente sur le site, les réseaux sociaux et les documents remis aux voyageurs.",
    organizationType: "business",
    projectStage: "launch",
    marketScope: "international",
    timeline: "three-plus-months",
    projectType: "complete-identity",
    brandProblem: "Les agences comparables utilisent souvent les mêmes photos et symboles. Orí doit paraître experte, accueillante et contemporaine sans donner l'impression d'un tourisme de masse.",
    difference: "Chaque itinéraire est construit avec des guides et lieux partenaires au Bénin ; les groupes sont limités à douze personnes et le prix explique clairement ce qui revient aux partenaires.",
    preserveAvoid: "Préserver la prononciation simple du nom et l'idée de lien. Éviter les silhouettes de carte d'Afrique, les motifs génériques et une image trop luxueuse.",
    creativeClarity: "3",
    namingState: "validated",
    brandArchitectureMode: "single",
    desiredAttributes: "Chaleureuse : on se sent attendu. Curieuse : elle invite à comprendre. Fiable : les informations sont nettes. Contemporaine : elle n'imite pas une imagerie traditionnelle figée.",
    visualReferences: "Nous aimons la sobriété éditoriale de Kinfolk et les couleurs franches de certaines affiches culturelles. Nous refusons les logos d'agence composés d'un avion et d'un globe.",
    inspirationLinks: "https://example.com/ori-voyages/moodboard\nhttps://example.com/ori-voyages/references-photo",
    logoStyles: ["wordmark", "combination"],
    colorPalette: ["#9B4A3F", "#E6B566", "#173F3A", "#F4EFE5"],
    colorDirection: "Privilégier des couleurs chaudes associées à un vert profond. Éviter le bleu d'agence de voyage et vérifier les contrastes pour les textes du site.",
    identityDeliverables: ["logo-suite", "visual-system", "usage-guide", "social-starter"],
    priorityApplications: ["social-media", "website", "sales-documents", "print"],
    technicalConstraints: "Français et anglais, lecture correcte sur mobile, logo utilisable en une couleur et fichiers adaptés à l'impression A4. L'imprimeur demande des PDF CMJN avec fond perdu.",
    rightsSources: ["digital-ready", "print-ready", "editable-sources", "provider-kit"],
    assetSources: ["brand-photos", "stock-library", "illustrations"],
    assetSupport: "organise-existing",
    projectLead: "Mélissa Adandé — Fondatrice — melissa.adande@example.com",
    finalDecisionMaker: "Mélissa Adandé — Fondatrice",
    contributors: "Le développeur du site recevra les règles web ; un guide partenaire relira les textes liés aux lieux.",
    validationProcess: "one",
    feedbackProcess: "Mélissa transmet un retour unique et annoté sous trois jours ouvrés après chaque présentation.",
    confidentiality: "Les itinéraires non annoncés et les tarifs négociés avec les partenaires ne doivent pas être diffusés avant le lancement.",
    successCriteria: "L'identité est reconnaissable sans cliché touristique, fonctionne sur mobile et en impression, et l'équipe peut produire les premiers supports à partir de la charte.",
    outOfScope: "Naming, développement du site, achat de photographies, impression et création de tous les supports futurs.",
    openQuestions: "Confirmer la disponibilité des photographies du premier circuit et choisir l'imprimeur du carnet de voyage.",
  },
  en: {
    projectName: "Ori Travel",
    activity: "Ori Travel creates small-group cultural journeys in Benin for the diaspora and French-speaking travellers.",
    projectTrigger: "The agency opens its first bookings in three months and needs an identity that builds trust before the website goes live.",
    primaryAudience: "Travellers aged 30 to 55 living in Europe or West Africa who want a serious cultural experience without an impersonal tour package.",
    businessObjective: "Launch with a distinctive, consistent image across the website, social media and documents given to travellers.",
    organizationType: "business",
    projectStage: "launch",
    marketScope: "international",
    timeline: "three-plus-months",
    projectType: "complete-identity",
    brandProblem: "Comparable agencies often use the same photographs and symbols. Ori must feel expert, welcoming and contemporary without suggesting mass tourism.",
    difference: "Every itinerary is built with guides and venue partners in Benin; groups are limited to twelve people and pricing clearly explains what supports local partners.",
    preserveAvoid: "Preserve the simple pronunciation of the name and the idea of connection. Avoid Africa map silhouettes, generic patterns and an overly luxurious image.",
    creativeClarity: "3",
    namingState: "validated",
    brandArchitectureMode: "single",
    desiredAttributes: "Warm: people feel expected. Curious: it invites understanding. Reliable: information is clear. Contemporary: it does not imitate a frozen traditional image.",
    visualReferences: "We like Kinfolk's editorial restraint and the bold colour of some cultural posters. We reject travel logos made from a plane and a globe.",
    inspirationLinks: "https://example.com/ori-travel/moodboard\nhttps://example.com/ori-travel/photo-references",
    logoStyles: ["wordmark", "combination"],
    colorPalette: ["#9B4A3F", "#E6B566", "#173F3A", "#F4EFE5"],
    colorDirection: "Favour warm colours with a deep green. Avoid standard travel-agency blue and verify text contrast on the website.",
    identityDeliverables: ["logo-suite", "visual-system", "usage-guide", "social-starter"],
    priorityApplications: ["social-media", "website", "sales-documents", "print"],
    technicalConstraints: "French and English, clear mobile use, a one-colour logo and files suitable for A4 printing. The printer requests bleed-ready CMYK PDFs.",
    rightsSources: ["digital-ready", "print-ready", "editable-sources", "provider-kit"],
    assetSources: ["brand-photos", "stock-library", "illustrations"],
    assetSupport: "organise-existing",
    projectLead: "Mélissa Adandé — Founder — melissa.adande@example.com",
    finalDecisionMaker: "Mélissa Adandé — Founder",
    contributors: "The website developer receives the web rules; one guide partner reviews copy related to places.",
    validationProcess: "one",
    feedbackProcess: "Mélissa sends one consolidated annotated response within three business days of each presentation.",
    confidentiality: "Unannounced itineraries and negotiated partner rates must not be shared before launch.",
    successCriteria: "The identity is recognisable without travel clichés, works on mobile and in print, and enables the team to create launch materials from the guide.",
    outOfScope: "Naming, website development, stock photography purchases, printing and production of every future asset.",
    openQuestions: "Confirm the availability of photographs from the first route and select the travel booklet printer.",
  },
};

export const CLIENT_BRIEF_DEMO_SCENARIOS: Record<ClientBriefTemplate["serviceKey"], LocalizedDemo> = {
  "editorial-strategy": editorialStrategy,
  "digital-communication": digitalCommunication,
  "content-creation": contentCreation,
  "audit-advice": auditAdvice,
  "visual-identity": visualIdentity,
};

export function buildClientBriefDemoAnswers(
  template: ClientBriefTemplate,
  locale: DemoLocale,
  partial = false,
): DemoAnswers {
  const fixture = CLIENT_BRIEF_DEMO_SCENARIOS[template.serviceKey]?.[locale] ?? {};
  const fields = template.sections.flatMap((section) => section.fields);
  const allowedKeys = new Set(fields.map((field) => field.key));
  const answers = Object.fromEntries(
    Object.entries(fixture).filter(([key]) => allowedKeys.has(key)),
  ) as DemoAnswers;

  for (const field of fields) {
    if (!isClientBriefFieldVisible(field, answers)) delete answers[field.key];
  }

  if (!partial) return answers;

  const visibleRequired = fields.filter(
    (field) => field.required && isClientBriefFieldVisible(field, answers),
  );
  for (const field of visibleRequired.slice(Math.ceil(visibleRequired.length / 2))) {
    delete answers[field.key];
  }
  return answers;
}
